### ISSUE TITLE
Add a UI

### ISSUE THREAD

**Issue by stilic** [badduck32/loverunner#1]
I don't know if it's technically possible, but this would be great to have, so people can have everything in one app.

**Comment by badduck32** [comment]
Sorry I only just noticed your comment

I have actually made an application with a UI to add different projects, but it doesn't work very well (I forgot why, it's been a while since I worked on that project), but I think one of the reasons I stopped developing that app is because in LÖVE 12 on Android there will be a lot more restrictions on which files on the device can and can't be accessed by the love app. Nonetheless, [here](https://github.com/badduck32/LOVE2D-Android-project-manager) is the repository for that project with a UI I was talking about.

Another way you could work around this issue (the way I do it) is to create multiple shortcuts and put them all inside 1 folder on your home screen.
If you have any further questions please don't hesitate to ask!

**Comment by stilic** [comment]
Alright
